spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    config:
      uri: http://localhost:8071
    loadbalancer:
      ribbon.enabled: false