spring:
  application:
    name: organization-service
  config:
    import: "optional:configserver:http://localhost:8071"
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071 # http://configserver:8071
